twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
      - 'form/button_field.html.twig'
      - 'form/input_field.html.twig'
      - 'form/select_field.html.twig'

    globals:
      random_header: '@App\Service\RandomHeader'
